<?php
/** @var $block Itransition_ShippingInsurance_Block_CheckoutInsurance */
$block = $this;
$costs = $block->listInsuranceCosts();
?>

<div class="itransition-shipping-insurance">
    <?php if ($block->isFeatureEnabled() && 0 < count($costs)): ?>
        <h3><?php echo $this->__('Do you want to add insurance for Shipping Method?'); ?></h3>
        <p class="control">
            <input type="checkbox" id="shippinginsurance_enabled" name="shippinginsurance_enabled" value="1">
            <label for="shippinginsurance_enabled"><?php echo $this->__('Yeah, got it, if possible.') ?></label>
        </p>
        <p><?php echo $this->__('List of all costs for supported insurance methods:'); ?></p>
        <table>
            <thead>
                <tr>
                    <td><?php echo $this->__('Method'); ?></td>
                    <td><?php echo $this->__('Insurance Cost'); ?></td>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($costs as $provider => $cost): ?>
                    <tr>
                        <td><?php echo $provider; ?></td>
                        <td><?php echo $cost; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>
